name: GeostatsPyDemosBook
channels:
  - default
dependencies:
  - python=3.8
  - sphinx
  - pip
  - pandas
  - matplotlib
  - pip:
    - quantecon
    - jupyter-book
    - pyvista
    - seaborn
    - imageio
    - astropy
    - tqdm
    - statsmodels
    - geostatspy

